import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          <p><Link href="./DataChartNext">データチャート（Next.js）</Link></p>
          <p><Link href="./CalendarNext">カレンダー（Next.js）</Link></p>
        </h1>        
      </main>

    </div>
  );
};

export default Home;
